version: 2.1

orbs:
  maven: circleci/maven@1.0.1

workflows:
  build: # build, test, resolve dependencies, and deploy if branch is main
    jobs:
      - maven/test:
          context: kgrid
          settings_file: ".circleci/settings.xml"
