version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  heroku: circleci/heroku@1.0.1

workflows:
  build:
    jobs:
      - maven/test:
          context: kgrid
          settings_file: ".circleci/settings.xml"
