version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  heroku: circleci/heroku@1.0.1

workflows:
  commit:
    jobs:
      - build-and-push
  earlymorning: # build and deploy main at the crack-o-dawn
    triggers:
      - schedule:
          cron: "0 10 * * 1-6"
          filters:
            branches:
              only:
                - main
    jobs:
      - maven/test:
          context: kgrid
          settings_file: ".circleci/settings.xml"
      - heroku/deploy-via-git:
          context: kgrid
          requires:
            - maven/test

jobs:
  build-and-push:
    machine: true
    steps:
      - checkout
      - maven/test:
          context: kgrid
          settings_file: ".circleci/settings.xml"
      - run: |
          mvn spring-boot:build-image
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD registry.aws.web.umich.edu
          docker tag kgrid-library registry.aws.web.umich.edu/kgrid-library/library:latest
          docker push registry.aws.web.umich.edu/kgrid-library/library:latest